package enumeration;

public enum Funcionalidade {
    INSERIR_FUNCIONARIO, IMPRIMIR_FUNCIONARIOS,REMOVER_FUNCIONARIO,
    APLICAR_AUMENTO, AGRUPAR_POR_FUNCAO,
    IMPRIMIR_ANIVERSARIANTES, IMPRIMIR_FUNC_MAIS_VELHO,
    IMPRIMIR_ORDEM_ALFABETICA, SOMAR_SALARIOS, IMPRIMIR_SALARIO_MINIMO;
}
